### ISSUE TITLE
Hello what steps mentioned at https://codelabs.developers.google.com/codelabs/angular-slider-element/index.html?index=..%2F..%2Findex#3

### ISSUE THREAD

**Issue by jsbimra** [aayusharora/angular-element-codelab#1]
The code in the downloaded zip and from git is not having exactly what is mention in step 3 and 4 of the course.

**Comment by tearforfear007** [comment]
In step 2, when I try to run the cli command with `ng serve` ,I get these error
```
Could not find module "@angular-devkit/build-angular" from "C:\\Users\\user\\Desktop\\YanYu\\angular-element-codelab-master\\image-slider".
Error: Could not find module "@angular-devkit/build-angular" from "C:\\Users\\user\\Desktop\\YanYu\\angular-element-codelab-master\\image-slider".
    at Object.resolve (C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\core\node\resolve.js:141:11)
    at Observable.rxjs_1.Observable [as _subscribe] (C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\src\architect.js:132:40)
    at Observable._trySubscribe (C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:43:25)
    at Observable.subscribe (C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:29:22)
    at DoOperator.call (C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\operators\tap.js:29:23)
    at Observable.subscribe (C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:24:22)
    at C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeTo.js:22:31
    at Object.subscribeToResult (C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:72:14)
```
To fix this, I run `npm install` before `ng serve`. And then `ng serve` works! Hope this help you.

**Comment by aayusharora** [comment]
Hi @jsbimra
Thanks for opening the issue.
Can you please explain the code difference, I will try to help you in that.

**Comment by emok032** [comment]
I agree with the OP.  There is a significant discrepancy between the lab instructions and the "finished" Github repo.

For example: the instructions indicate the use of data.json to store the sliderArray object but it's not even in the Github repo.  Also, there is no service being used in the final code as instructed in the code lab.

Please clarify, thank you!

**Comment by emok032** [comment]
![screenshot](https://user-images.githubusercontent.com/17553357/52082345-8a62c280-256a-11e9-9fef-686df44b715b.JPG)

Cant these two steps be clarified? Was it meant to be something else?

> To initialize:
> 
> constructor(private data: DataService) {
>  this.sliderArray = [];
> }
> Next, we need to import and initialize our service inside the constructor
> 
> constructor(private data: DataService) {
>  }

**Comment by emok032** [comment]
Here's a minor discrepancy.  Prior to this section, there is no mention of a selectedIndex variable in the slider.component.  The creation of this variable seems to be implied in these instructions.

![image](https://user-images.githubusercontent.com/17553357/52082882-f72a8c80-256b-11e9-994f-cd27ed07da21.png)

**Comment by emok032** [comment]
Where is this "Result" type being defined and where is the subscription being implemented? This entire section does not exist in the final code.

![image](https://user-images.githubusercontent.com/17553357/52084414-0b708880-2570-11e9-9504-d5338e6aa3a3.png)

**Comment by aayusharora** [comment]
> For example: the instructions indicate the use of data.json to store the sliderArray object but it's not even in the Github repo. Also, there is no service being used in the final code as instructed in the code lab.

data.json added to assets/

**Comment by aayusharora** [comment]
> Also, there is no service being used in the final code as instructed in the code lab.

Final code updated with data Service

**Comment by aayusharora** [comment]
> Cant these two steps be clarified? Was it meant to be something else?

Here you just need to fetch the data using the dataService now added in the image-slider directory.

**Comment by aayusharora** [comment]
> Where is this "Result" type being defined and where is the subscription being implemented? This entire section does not exist in the final code.

The result.ts is added to help you with the type checking :)

**Comment by aayusharora** [comment]
@emok032 Thanks for reporting.
Please check, if you are able to complete this now.
Let me know, in case we need to improve more.

**Comment by emok032** [comment]
@aayusharora Thanks for updating this! When I try to run it, an error is returned to the console:

![image](https://user-images.githubusercontent.com/17553357/52222488-9bb11500-2871-11e9-877e-00b874d16852.png)

Packages were installed and I am running it on node v.10.11.0.

*Update: I was running the skeleton version before,.  The final version produces no error in the console but nothing is rendering on the browser.

**Comment by aayusharora** [comment]
Hi @emok032 
After running the command `npm run build`
You will find dist folder, which you can run with a http-server.
Remember the component name defined inside index.html of dist should be
```
<motley-slider></motley-slider>
```
and not 
```
<app-root></app-root>
```

**Comment by emok032** [comment]
Thanks @aayusharora 
But does it only work if it's on the index page? Why can't this be visible in a real-world scenario where this slider is located in a component? To be reused elsewhere.

**Comment by emok032** [comment]
"serve": "http-server"

so I used the command: "npm run serve" which returns this error:

> 'http-server' is not recognized as an internal or external command,
> operable program or batch file.

I'm running the final build of your repo.

*Update: It seems that 'http-server' needs to be added to the package.json.  Can this be added to the official repo? But still the motley-slider does not render.

**Comment by aayusharora** [comment]
It is weird @emok032 
motley-slider will work everywhere wherever you will include element.js file 
or
when you package, the dist you get will work everywhere. 
You can try hosting it anywhere or try running the dist using http-server on localhost.

**Comment by emok032** [comment]
Thanks @aayusharora 

I've been running http-server in the Final code app and nothing appears.

**Comment by aayusharora** [comment]
Welcome,
I hope, this is resolved now :)

**Comment by emok032** [comment]
Hi, since my last message still nothing appears.  Do you have a screenshot of what it should look like.  The app runs without throwing any errors but only produces a blank page at localhost:4200

**Comment by emok032** [comment]
Hi @aayusharora 

I've forked the repo and committed changes for a PR.  The slider is now appearing.  Needed the motley-slider directive in the other index.html.  Thanks for the work thus far.  It's much appreciated it.

**Comment by aayusharora** [comment]
Awesome, thanks for your support.
Merged
