### ISSUE TITLE
Step 1 typos

### ISSUE THREAD

**Issue by freewheelnat** [aayusharora/angular-element-codelab#2]
Noticed a couple of typos:

1) Just below the video, it says "Your element wi:". It should say "Your element will:"

2) Then it says "Able to plugged in any framework that talks to the DOM". It should say "be able to plug in any framework that talks to the DOM".

**Comment by aayusharora** [comment]
Hi @freewheelnat 
Thanks a lot for the suggestions :)
Would you like to work on this?

**Comment by freewheelnat** [comment]
Sorry, I haven't got time to work on this at the moment
