### ISSUE TITLE
Code not working: Is this lab's code going to be revised/updated?

### ISSUE THREAD

**Issue by emok032** [aayusharora/angular-element-codelab#5]
Will this lab's code be revised and debugged as listed in this thread ([https://github.com/aayusharora/angular-element-codelab/issues/1])?

**Comment by aayusharora** [comment]
Hi @emok032 
I am working on this right now.
Thanks for creating issue.

**Comment by emok032** [comment]
Thank you, much appreciated!

**Comment by aayusharora** [comment]
I just completed the codelab myself and updated the code.
Thanks for reporting.
